"""
View recommendations generated by Agent B
"""

import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from database.connection import get_collection, HEALTH_ADVICE_COLLECTION

def view_recommendations():
    """Display all recommendations from MongoDB."""
    collection = get_collection(HEALTH_ADVICE_COLLECTION)
    
    recommendations = list(collection.find())
    
    print("=" * 70)
    print(f"HEALTH RECOMMENDATIONS - {len(recommendations)} total")
    print("=" * 70)
    
    for rec in recommendations:
        print(f"\n{'='*70}")
        print(f"USER: {rec['user_id']}")
        print(f"{'='*70}")
        print(f"Anomaly: {rec['anomaly_report']['metric']} dropped {rec['anomaly_report']['drop_percentage']}%")
        print(f"Severity: {rec['anomaly_report']['severity'].upper()}")
        print(f"RAG Sources: {', '.join(rec['rag_sources'])}")
        print(f"Created: {rec['created_at']}")
        print(f"\nRECOMMENDATION:")
        print(rec['recommendation'])
        print()

if __name__ == "__main__":
    view_recommendations()
